# Generated by Django 3.2.9 on 2021-11-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productDescription', models.CharField(max_length=300)),
                ('productIngredients', models.CharField(max_length=300)),
                ('productPrice', models.FloatField()),
                ('productPhoto', models.ImageField(upload_to='')),
                ('productCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.category')),
            ],
        ),
    ]
