# Generated by Django 3.2.9 on 2022-01-11 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Неподдерживаемый номер телефона пользователя (только вид (+7-8) (8-9)хх ххх хх хх)', regex='[+7|8][8|9][0-9]{9}')], verbose_name='Номер телефона'),
        ),
    ]
