# Generated by Django 3.2.9 on 2022-01-11 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_key', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Увы, но акции с таким кодом просто нет', regex='[a-zA-Z0-9]{10}')], verbose_name='Код акции')),
                ('stock_value', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки')),
                ('stock_product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.product')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['id'],
            },
        ),
    ]
