# Generated by Django 3.2.9 on 2022-01-11 15:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_cost'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_key',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Недопустимый вид кода акции - ровно 10 символов', regex='[a-zA-Z0-9]{10}')], verbose_name='Код акции'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Акционный товар'),
        ),
    ]
