# Generated by Django 3.2.9 on 2022-01-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_stock_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_key',
            field=models.CharField(max_length=10, verbose_name='Код акции'),
        ),
    ]
