# Generated by Django 3.2.9 on 2022-01-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=50, verbose_name='Профессия')),
                ('discription', models.CharField(max_length=400, verbose_name='Предложение')),
                ('salary', models.IntegerField(default=10000, verbose_name='Заработная плата')),
                ('image', models.ImageField(upload_to='VacancyImages', verbose_name='Фото')),
                ('is_open', models.BooleanField(default=True, verbose_name='Актуальность')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'ordering': ['salary'],
            },
        ),
    ]
