version: "3.9"
services:
  bot:
      build:
        context: . 
        dockerfile: Dockerfile
      command: bash -c "python telegram_bot.py"
      depends_on:
        - "db"
  db:
      image: postgres:13.3
      container_name: postgres
      environment:
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      restart: always
      ports:
        - 5432:5432
